# Reference: https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#github-actions
name: Update README cards

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # necessary for amend to last commit to work
          fetch-depth: 2

      - name: Generate shoes-light.svg
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=shoes
          path: profile/shoes-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate shoes-dark.svg
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=shoes&theme=dark
          path: profile/shoes-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tobaru-light.svg
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=tobaru
          path: profile/tobaru-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tobaru-dark.svg
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=tobaru&theme=dark
          path: profile/tobaru-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          if [ "$(git log -1 --format=%s)" = "Update README cards" ]; then
            git commit --amend --no-edit || exit 0
            git push --force-with-lease
          else
            git commit -m "Update README cards" || exit 0
            git push
          fi
